@echo off
cd %~dp0\soil_ai_system
echo Starting Soil Intelligence System Enterprise Frontend...
echo Enforcing Virtual Environment usage...
..\.venv\Scripts\python.exe -m streamlit run app\app.py
pause
